export const USER_LOGIN = 'AUTH/USER_LOGIN';
export const USER_LOGOUT = 'AUTH/USER_LOGOUT';
export const USER_AUTH_LOAD = 'AUTH/USER_AUTH_LOAD';

export const SHOW_LOADER = 'APP/SHOW_LOADER';
export const HIDE_LOADER = 'APP/HIDE_LOADER';
export const SHOW_LINE_LOADER = 'APP/SHOW_LINE_LOADER';
export const HIDE_LINE_LOADER = 'APP/HIDE_LINE_LOADER';
export const SHOW_ERROR = 'APP/SHOW_ERROR';
export const HIDE_ERROR = 'APP/HIDE_ERROR';
export const SHOW_SUCCESS = 'APP/SHOW_SUCCESS';
export const HIDE_SUCCESS = 'APP/HIDE_SUCCESS';
export const HTTP_404_ERROR = 'APP/HTTP_404_ERROR';
